controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
alt_controller:
    path: /alt
    controller: App\Controller\SubController\AltController
